-- Add video support to product_images table
-- This allows products to have videos in their gallery (with thumbnails for fast loading)

-- Add media type enum
DO $$ BEGIN
  CREATE TYPE media_type AS ENUM ('image', 'video');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Add mediaType column (default 'image' for backward compatibility)
ALTER TABLE product_images 
ADD COLUMN IF NOT EXISTS media_type media_type DEFAULT 'image' NOT NULL;

-- Add thumbnailUrl for video thumbnails (generated by Cloudinary)
ALTER TABLE product_images 
ADD COLUMN IF NOT EXISTS thumbnail_url varchar(500);

-- Add duration for videos (in seconds, optional metadata)
ALTER TABLE product_images 
ADD COLUMN IF NOT EXISTS duration integer;

-- Comment for documentation
COMMENT ON COLUMN product_images.media_type IS 'Type of media: image or video';
COMMENT ON COLUMN product_images.thumbnail_url IS 'Thumbnail URL for videos (auto-generated from first frame)';
COMMENT ON COLUMN product_images.duration IS 'Video duration in seconds (optional)';

